### ISSUE TITLE
r/speziscool???

### ISSUE THREAD

**Issue by lokzz** [reddark-remix/reddark-remix#32]
why
![image](https://github.com/reddark-remix/reddark-remix/assets/50368061/c1bffa22-3169-4ba1-9778-74be14811657)
![image](https://github.com/reddark-remix/reddark-remix/assets/50368061/507f3414-a007-4d2d-819d-4eb4190e38b4)

**Comment by username-is-required** [comment]
i have no idea why that sub’s in the list, especially as it doesn’t actually seem to exist - whether it’s an easter egg by modcood, or it slipped through the net when they were compiling the list, who knows. i had to [hard-code it out](https://github.com/username-is-required/reddark/blob/b94a785a323916b2513a1de93c1d46e007d65c13/main.js#L95-L96) of my fork so that it didn’t cause my autoupdating system any problems lol

**Comment by minusQuantumNeko** [comment]
I'll contact r/ModCoord team about that
